#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ContextGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AspNet.Identity.TelerikDataAccess.MSSQL.DBEntities;

namespace AspNet.Identity.TelerikDataAccess.MSSQL.DBEntities	
{
	public partial class IdentityModel : OpenAccessContext, IIdentityModelUnitOfWork
	{
		private static string connectionStringName = @"AspNetIdentityConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
				
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("IdentityModel.rlinq");
		
		public IdentityModel()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public IdentityModel(string connection)
			:base(connection, backend, metadataSource)
		{ }
		
		public IdentityModel(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public IdentityModel(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public IdentityModel(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<UserLogin> UserLogins 
		{
			get
			{
				return this.GetAll<UserLogin>();
			}
		}
		
		public IQueryable<UserClaim> UserClaims 
		{
			get
			{
				return this.GetAll<UserClaim>();
			}
		}
		
		public IQueryable<User> Users 
		{
			get
			{
				return this.GetAll<User>();
			}
		}
		
		public IQueryable<Role> Roles 
		{
			get
			{
				return this.GetAll<Role>();
			}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "MsSql";
			backend.ProviderName = "System.Data.SqlClient";
		
			CustomizeBackendConfiguration(ref backend);
		
			return backend;
		}
		
		/// <summary>
		/// Allows you to customize the BackendConfiguration of IdentityModel.
		/// </summary>
		/// <param name="config">The BackendConfiguration of IdentityModel.</param>
		static partial void CustomizeBackendConfiguration(ref BackendConfiguration config);
		
	}
	
	public interface IIdentityModelUnitOfWork : IUnitOfWork
	{
		IQueryable<UserLogin> UserLogins
		{
			get;
		}
		IQueryable<UserClaim> UserClaims
		{
			get;
		}
		IQueryable<User> Users
		{
			get;
		}
		IQueryable<Role> Roles
		{
			get;
		}
	}
}
#pragma warning restore 1591
