#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using AspNet.Identity.TelerikDataAccess.MSSQL.DBEntities;

namespace AspNet.Identity.TelerikDataAccess.MSSQL.DBEntities	
{
	public partial class User
	{
		private int _id;
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private bool _emailConfirmed;
		public virtual bool EmailConfirmed
		{
			get
			{
				return this._emailConfirmed;
			}
			set
			{
				this._emailConfirmed = value;
			}
		}
		
		private string _passwordHash;
		public virtual string PasswordHash
		{
			get
			{
				return this._passwordHash;
			}
			set
			{
				this._passwordHash = value;
			}
		}
		
		private string _securityStamp;
		public virtual string SecurityStamp
		{
			get
			{
				return this._securityStamp;
			}
			set
			{
				this._securityStamp = value;
			}
		}
		
		private string _phoneNumber;
		public virtual string PhoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				this._phoneNumber = value;
			}
		}
		
		private bool _phoneNumberConfirmed;
		public virtual bool PhoneNumberConfirmed
		{
			get
			{
				return this._phoneNumberConfirmed;
			}
			set
			{
				this._phoneNumberConfirmed = value;
			}
		}
		
		private bool _twoFactorEnabled;
		public virtual bool TwoFactorEnabled
		{
			get
			{
				return this._twoFactorEnabled;
			}
			set
			{
				this._twoFactorEnabled = value;
			}
		}
		
		private DateTime? _lockoutEndDateUtc;
		public virtual DateTime? LockoutEndDateUtc
		{
			get
			{
				return this._lockoutEndDateUtc;
			}
			set
			{
				this._lockoutEndDateUtc = value;
			}
		}
		
		private bool _lockoutEnabled;
		public virtual bool LockoutEnabled
		{
			get
			{
				return this._lockoutEnabled;
			}
			set
			{
				this._lockoutEnabled = value;
			}
		}
		
		private int _accessFailedCount;
		public virtual int AccessFailedCount
		{
			get
			{
				return this._accessFailedCount;
			}
			set
			{
				this._accessFailedCount = value;
			}
		}
		
		private string _userName;
		public virtual string UserName
		{
			get
			{
				return this._userName;
			}
			set
			{
				this._userName = value;
			}
		}
		
		private IList<UserLogin> _userLogins = new List<UserLogin>();
		public virtual IList<UserLogin> UserLogins
		{
			get
			{
				return this._userLogins;
			}
		}
		
		private IList<UserClaim> _userClaims = new List<UserClaim>();
		public virtual IList<UserClaim> UserClaims
		{
			get
			{
				return this._userClaims;
			}
		}
		
		private IList<Role> _roles = new List<Role>();
		public virtual IList<Role> Roles
		{
			get
			{
				return this._roles;
			}
		}
		
	}
}
#pragma warning restore 1591
